name: Mariomalpica
favicon: null
layout_spectrum: 0.03503092494793236
typography_spectrum: 0.9625920110847801
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.33367210859432817
  lightness: 0.3095714570954442
  saturation: 0.8713596840389073
  rhythmicContrast: 0.32240499719046056
purpose: []
