analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8713596840389073
  lightness: 0.3095714570954442
  brandStrength: 0.8254564
  brandColors:
    - '#F3F3F3'
    - '#9A9A9A'
    - '#020202'
    - '#AC271E'
    - '#165BB4'
  rhythmicContrast: 0.3224049971904606
typography_spectrum: 0.1863587
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9994629
favicon: null
name: Mariomalpica
